# Generated by Django 3.0.5 on 2020-11-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khojadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='PendingUrl',
        ),
    ]
