# Generated by Django 3.0.3 on 2020-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200310_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='priority',
            field=models.FloatField(default=1.0),
        ),
    ]
