# Generated by Django 3.0.5 on 2020-11-11 14:28

from django.db import migrations
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201111_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sites',
        ),
        migrations.RemoveField(
            model_name='indexing',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='indexing',
            name='site_ids',
        ),
        migrations.AddField(
            model_name='indexing',
            name='file',
            field=djongo.models.fields.EmbeddedField(default='', model_container=home.models.sites),
        ),
        migrations.AddField(
            model_name='indexing',
            name='previous_keys',
            field=djongo.models.fields.ArrayField(default='', model_container=home.models.Key),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='key',
            field=djongo.models.fields.EmbeddedField(default='', model_container=home.models.Key),
        ),
    ]
