# Generated by Django 3.0.3 on 2020-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sites_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='uncrawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=255)),
                ('links', models.TextField()),
            ],
        ),
    ]
