# Generated by Django 3.0.5 on 2020-11-11 14:35

from django.db import migrations
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201111_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexing',
            name='file',
            field=djongo.models.fields.EmbeddedField(default={'description': '', 'display': True, 'domain': '.com', 'icon': '/favicon.ico', 'indexed': False, 'priority': 1.0, 'title': '', 'url': '', 'visit_count': 0, 'word_links': ''}, model_container=home.models.sites),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='key',
            field=djongo.models.fields.EmbeddedField(default={'key': ''}, model_container=home.models.Key),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='previous_keys',
            field=djongo.models.fields.ArrayField(default=['', 0, 0], model_container=home.models.Key),
        ),
    ]
