# Generated by Django 3.0.5 on 2020-11-11 14:37

from django.db import migrations
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201111_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexing',
            name='file',
            field=djongo.models.fields.EmbeddedField(model_container=home.models.sites, null=True),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='key',
            field=djongo.models.fields.EmbeddedField(model_container=home.models.Key, null=True),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='previous_keys',
            field=djongo.models.fields.ArrayField(model_container=home.models.Key, null=True),
        ),
    ]
