# Generated by Django 3.0.3 on 2020-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uncrawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
