# Generated by Django 3.0.3 on 2020-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200312_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference_directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=255)),
                ('category', models.BinaryField()),
                ('length', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='reference_dir',
            field=models.TextField(default='khoj_contents/content1', max_length=255),
        ),
    ]
