# Generated by Django 3.0.3 on 2020-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200314_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='file_name',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reference_directory',
            name='category',
            field=models.BinaryField(default=10),
        ),
    ]
