# Generated by Django 3.0.3 on 2020-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200314_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_directory',
            name='category',
            field=models.IntegerField(default=10),
        ),
    ]
