# Generated by Django 3.0.3 on 2020-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200314_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='desc',
            field=models.TextField(max_length=400),
        ),
    ]
