# Generated by Django 3.0.3 on 2020-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200314_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='desc',
            field=models.CharField(max_length=400),
        ),
    ]
