# Generated by Django 3.0.6 on 2020-05-16 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200417_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('desc', models.TextField()),
                ('report_date', models.DateField(default=datetime.datetime(2020, 5, 16, 4, 5, 49, 996843, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='reference_directory',
        ),
    ]
