# Generated by Django 3.0.6 on 2020-06-28 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200516_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='reference_dir',
        ),
        migrations.AddField(
            model_name='sites',
            name='words_links',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 28, 5, 11, 9, 4561, tzinfo=utc)),
        ),
    ]
