# Generated by Django 3.0.6 on 2020-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200628_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='icon',
            field=models.CharField(default='/favicon.ico', max_length=255),
        ),
    ]
