# Generated by Django 3.1 on 2020-09-04 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_feedback_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexerSecondary',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
