# Generated by Django 3.1 on 2020-09-04 11:35

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200904_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='related_desc',
            field=models.CharField(default=home.models.feedback.least_desc, max_length=33),
        ),
    ]
