# Generated by Django 3.1 on 2020-09-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_feedback_related_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='related_desc',
        ),
    ]
